<a href="https://colab.research.google.com/github/nkarthikn95/EDA-Hotel-Bookings-Capstone-project1/blob/main/Hotel_Booking_Analysis2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Loading data 
file_path = '/content/drive/MyDrive/EDA Capstone Project/Hotel Bookings (1).csv'
cp_df=pd.read_csv(file_path)


In [ ]:
#check the decoration
cp_df.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'company', 'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date'],
      dtype='object')

In [ ]:
# Data at glance
cp_df.head()

hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit   
1                        0                     0       2  ...    No Deposit   
2                        0                     1       1  ...    No Deposit   
3                        0                     1       1  ...    No Deposit   
4                        0                     2       2  ...    No Deposit   

   agent company days_in_waiting_list customer_type   adr  \
0    NaN     NaN                    0     Transient   0.0   
1    NaN     NaN                    0     Transient   0.0   
2    NaN     NaN                    0     Transient  75.0   
3  304.0     NaN                    0     Transient  75.0   
4  240.0     NaN                    0     Transient  98.0   

   required_car_parking_spaces  total_of_special_requests  reservation_status  \
0                            0                          0           Check-Out   
1                            0                          0           Check-Out   
2                            0                          0           Check-Out   
3                            0                          0           Check-Out   
4                            0                          1           Check-Out   

  reservation_status_date  
0              2015-07-01  
1              2015-07-01  
2              2015-07-02  
3              2015-07-02  
4              2015-07-03  

[5 rows x 32 columns]

In [ ]:
cp_df.tail()

hotel  is_canceled  lead_time  arrival_date_year  \
119385  City Hotel            0         23               2017   
119386  City Hotel            0        102               2017   
119387  City Hotel            0         34               2017   
119388  City Hotel            0        109               2017   
119389  City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
119385             August                        35   
119386             August                        35   
119387             August                        35   
119388             August                        35   
119389             August                        35   

        arrival_date_day_of_month  stays_in_weekend_nights  \
119385                         30                        2   
119386                         31                        2   
119387                         31                        2   
119388                         31                        2   
119389                         29                        2   

        stays_in_week_nights  adults  ...  deposit_type  agent company  \
119385                     5       2  ...    No Deposit  394.0     NaN   
119386                     5       3  ...    No Deposit    9.0     NaN   
119387                     5       2  ...    No Deposit    9.0     NaN   
119388                     5       2  ...    No Deposit   89.0     NaN   
119389                     7       2  ...    No Deposit    9.0     NaN   

       days_in_waiting_list customer_type     adr  \
119385                    0     Transient   96.14   
119386                    0     Transient  225.43   
119387                    0     Transient  157.71   
119388                    0     Transient  104.40   
119389                    0     Transient  151.20   

        required_car_parking_spaces  total_of_special_requests  \
119385                            0                          0   
119386                            0                          2   
119387                            0                          4   
119388                            0                          0   
119389                            0                          2   

        reservation_status reservation_status_date  
119385           Check-Out              2017-09-06  
119386           Check-Out              2017-09-07  
119387           Check-Out              2017-09-07  
119388           Check-Out              2017-09-07  
119389           Check-Out              2017-09-07  

[5 rows x 32 columns]

In [ ]:
cp_df.shape

(119390, 32)

In [ ]:
cp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [ ]:
cp_df.describe().T

count         mean         std      min  \
is_canceled                     119390.0     0.370416    0.482918     0.00   
lead_time                       119390.0   104.011416  106.863097     0.00   
arrival_date_year               119390.0  2016.156554    0.707476  2015.00   
arrival_date_week_number        119390.0    27.165173   13.605138     1.00   
arrival_date_day_of_month       119390.0    15.798241    8.780829     1.00   
stays_in_weekend_nights         119390.0     0.927599    0.998613     0.00   
stays_in_week_nights            119390.0     2.500302    1.908286     0.00   
adults                          119390.0     1.856403    0.579261     0.00   
children                        119386.0     0.103890    0.398561     0.00   
babies                          119390.0     0.007949    0.097436     0.00   
is_repeated_guest               119390.0     0.031912    0.175767     0.00   
previous_cancellations          119390.0     0.087118    0.844336     0.00   
previous_bookings_not_canceled  119390.0     0.137097    1.497437     0.00   
booking_changes                 119390.0     0.221124    0.652306     0.00   
agent                           103050.0    86.693382  110.774548     1.00   
company                           6797.0   189.266735  131.655015     6.00   
days_in_waiting_list            119390.0     2.321149   17.594721     0.00   
adr                             119390.0   101.831122   50.535790    -6.38   
required_car_parking_spaces     119390.0     0.062518    0.245291     0.00   
total_of_special_requests       119390.0     0.571363    0.792798     0.00   

                                    25%       50%     75%     max  
is_canceled                        0.00     0.000     1.0     1.0  
lead_time                         18.00    69.000   160.0   737.0  
arrival_date_year               2016.00  2016.000  2017.0  2017.0  
arrival_date_week_number          16.00    28.000    38.0    53.0  
arrival_date_day_of_month          8.00    16.000    23.0    31.0  
stays_in_weekend_nights            0.00     1.000     2.0    19.0  
stays_in_week_nights               1.00     2.000     3.0    50.0  
adults                             2.00     2.000     2.0    55.0  
children                           0.00     0.000     0.0    10.0  
babies                             0.00     0.000     0.0    10.0  
is_repeated_guest                  0.00     0.000     0.0     1.0  
previous_cancellations             0.00     0.000     0.0    26.0  
previous_bookings_not_canceled     0.00     0.000     0.0    72.0  
booking_changes                    0.00     0.000     0.0    21.0  
agent                              9.00    14.000   229.0   535.0  
company                           62.00   179.000   270.0   543.0  
days_in_waiting_list               0.00     0.000     0.0   391.0  
adr                               69.29    94.575   126.0  5400.0  
required_car_parking_spaces        0.00     0.000     0.0     8.0  
total_of_special_requests          0.00     0.000     1.0     5.0

In [ ]:
df=cp_df.copy()


In [ ]:
df['hotel'].unique()

array(['Resort Hotel', 'City Hotel'], dtype=object)

In [ ]:
df['is_canceled'].unique()

array([0, 1])

In [ ]:
df['is_canceled'].unique()

array([0, 1])

In [ ]:
df['arrival_date_year'].unique()

array([2015, 2016, 2017])

In [ ]:
df['meal'].unique()

array(['BB', 'FB', 'HB', 'SC', 'Undefined'], dtype=object)

In [ ]:
df['market_segment'].unique()

array(['Direct', 'Corporate', 'Online TA', 'Offline TA/TO',
       'Complementary', 'Groups', 'Undefined', 'Aviation'], dtype=object)

In [ ]:
df['distribution_channel'].unique()

array(['Direct', 'Corporate', 'TA/TO', 'Undefined', 'GDS'], dtype=object)

In [ ]:
df['children'].unique() 

array([ 0.,  1.,  2., 10.,  3., nan])

In [ ]:
# Cleaning the Data 

df[df.duplicated()].shape 

(31994, 32)

In [ ]:
# Dropping duplicate values
df.drop_duplicates(inplace = True)

In [ ]:
df.shape

(87396, 32)

In [ ]:
df.isnull().sum().sort_values

<bound method Series.sort_values of hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              4
babies                                0
meal                                  0
country                             452
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             12193
comp

In [ ]:
# Handling Missing data

missing_data = pd.DataFrame([df.isnull().sum(),df.isnull().sum()*100.0/df.shape[0]]).T
missing_data.columns = ['No. of Missing Data', '% Missing Data']
missing_data

No. of Missing Data  % Missing Data
hotel                                           0.0        0.000000
is_canceled                                     0.0        0.000000
lead_time                                       0.0        0.000000
arrival_date_year                               0.0        0.000000
arrival_date_month                              0.0        0.000000
arrival_date_week_number                        0.0        0.000000
arrival_date_day_of_month                       0.0        0.000000
stays_in_weekend_nights                         0.0        0.000000
stays_in_week_nights                            0.0        0.000000
adults                                          0.0        0.000000
children                                        0.0        0.000000
babies                                          0.0        0.000000
meal                                            0.0        0.000000
country                                         0.0        0.000000
market_segment                                  0.0        0.000000
distribution_channel                            0.0        0.000000
is_repeated_guest                               0.0        0.000000
previous_cancellations                          0.0        0.000000
previous_bookings_not_canceled                  0.0        0.000000
reserved_room_type                              0.0        0.000000
assigned_room_type                              0.0        0.000000
booking_changes                                 0.0        0.000000
deposit_type                                    0.0        0.000000
agent                                       12193.0       13.951439
company                                     82137.0       93.982562
days_in_waiting_list                            0.0        0.000000
customer_type                                   0.0        0.000000
adr                                             0.0        0.000000
required_car_parking_spaces                     0.0        0.000000
total_of_special_requests                       0.0        0.000000
reservation_status                              0.0        0.000000
reservation_status_date                         0.0        0.000000

0.004% of rows have missing data in children column. Now we will look at the distribution of this missing data.

In [ ]:
df['children'].value_counts()

0.0     79028
1.0      4695
2.0      3593
3.0        75
10.0        1
Name: children, dtype: int64

Most booking had no children and hence we will fill the missing rows for the children with 0



In [ ]:
df['children'].fillna(0,inplace=True)

0.5% of rows have missing data in country column. Now we will look at the distribution of this missing information.

In [ ]:
country_data = pd.DataFrame([df['country'].value_counts(),df['country'].value_counts()*100/df.shape[0]]).T
country_data.columns = ['Count', '% Distribution']
country_data

Count  % Distribution
PRT  27453.0       31.412193
GBR  10433.0       11.937617
FRA   8837.0       10.111447
ESP   7252.0        8.297863
DEU   5387.0        6.163898
..       ...             ...
MMR      1.0        0.001144
BFA      1.0        0.001144
CYM      1.0        0.001144
MLI      1.0        0.001144
KHM      1.0        0.001144

[178 rows x 2 columns]

In [ ]:
df['country'].fillna('NaN',inplace=True)

In [ ]:
df['agent'].fillna('NaN',inplace=True)
df ['company'].fillna('NaN',inplace=True)

Let's confirm all missing data have been handled

In [ ]:
perc_missing_data = pd.DataFrame([df.isnull().sum(),df.isnull().sum()*100.0/df.shape[0]]).T
perc_missing_data.columns = ['No. of Missing Data', '% Missing Data']
perc_missing_data

No. of Missing Data  % Missing Data
hotel                                           0.0             0.0
is_canceled                                     0.0             0.0
lead_time                                       0.0             0.0
arrival_date_year                               0.0             0.0
arrival_date_month                              0.0             0.0
arrival_date_week_number                        0.0             0.0
arrival_date_day_of_month                       0.0             0.0
stays_in_weekend_nights                         0.0             0.0
stays_in_week_nights                            0.0             0.0
adults                                          0.0             0.0
children                                        0.0             0.0
babies                                          0.0             0.0
meal                                            0.0             0.0
country                                         0.0             0.0
market_segment                                  0.0             0.0
distribution_channel                            0.0             0.0
is_repeated_guest                               0.0             0.0
previous_cancellations                          0.0             0.0
previous_bookings_not_canceled                  0.0             0.0
reserved_room_type                              0.0             0.0
assigned_room_type                              0.0             0.0
booking_changes                                 0.0             0.0
deposit_type                                    0.0             0.0
agent                                           0.0             0.0
company                                         0.0             0.0
days_in_waiting_list                            0.0             0.0
customer_type                                   0.0             0.0
adr                                             0.0             0.0
required_car_parking_spaces                     0.0             0.0
total_of_special_requests                       0.0             0.0
reservation_status                              0.0             0.0
reservation_status_date                         0.0             0.0